# name: Magic Message

# on:
#   workflow_dispatch:
#   //push:
    
# jobs:
#   magic:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v3

#       - 
#       if: "!contains(github.event.head_commit.message, 'build')"
    
    