name: Main with subflow

on:
  - push

jobs:
  build:
    name: Run sub workflow
    uses: ./.github/workflows/sub_flow.yml
    with:
      simulate-build: true
  
  boolean_test:
    runs-on: ubuntu-latest
    name: Boolean Test
    env: 
      is-connected: true
    steps:
      - name: Reacts on boolean
        if: ${{ env.is-connected == 'true' }}
        run: echo "Is true"

  variable_test:
    runs-on: ubuntu-latest
    name: Variables Test
    steps:
      - run: |
          SET JOB_ID=12345
          echo $JOB_ID

      - run: echo $JOB_ID