# This is a basic workflow to help you get started with Actions

name: Dependent Jobs

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main", "de*" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!
  deployStaging: 
    name: Deploy to staging
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy with staging settings
        run: echo Deploying system
  endToEnd:
    name: End To End Tests
    needs: deploy
    runs-on: ubuntu-latest
    steps: 
      - name: Run a Postman runner with defined scripts
        run: echo Running Postman
  deployProduction:
    name: Deploy to productions
    needs: endToEnd
    runs-on: ubuntu-latest
    steps:
      - name: Run deploy script with production settings
        run: echo Running Postman