name: Release

# Only run when a release is created: Change the pre-release to release and this flow should run.

on:
  release: 
    types:
    - released

jobs:
  release: 
    name: Release
    runs-on: ubuntu-latest
    steps:
      - run: echo Release to production
      
      - name: Download assets
        uses: robinraju/release-downloader@v1.10
        with:
          repository: ${{ github.repository }}
          tag: ${{ github.ref_name }}
          fileName: 'README.md'
  
  dump_contexts_to_log:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"